---
# tasks file for ansible-role-certbot-auto
- name: Install wget
  apt:
    name: wget
    state: present
    update_cache: yes
- name: Get certbot-auto
  get_url:
    url: https://dl.eff.org/certbot-auto
    dest: /usr/local/bin/certbot-auto
- name: Set permissions
  file:
    path: /usr/local/bin/certbot-auto
    owner: root
    mode: '0755'
- name: Install Certbot Dependencies
  shell: yes |/usr/local/bin/certbot-auto --install-only
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
- name: Install Google DNS Plugin
  pip:
    executable: /opt/eff.org/certbot/venv/bin/pip
    name: certbot-dns-google
  when: google_dns_plugin
